### PR TITLE
cassandra: log in console when search enabled, but SASI disabled

### LINKED ISSUE #3412: table doesn't exist in 2.23.15
## Describe the Bug
A clear and concise description of what the bug is. If you have a solution in mind, skip raising an issue and open a pull request instead.

Started zipkin with an already existing cassandra instance, with `CASSANDRA_ENSURE_SCHEMA`. The logs indicate the migrations are run:

```

                  oo
                 oooo
                oooooo
               oooooooo
              oooooooooo
             oooooooooooo
           ooooooo  ooooooo
          oooooo     ooooooo
         oooooo       ooooooo
        oooooo   o  o   oooooo
       oooooo   oo  oo   oooooo
     ooooooo  oooo  oooo  ooooooo
    oooooo   ooooo  ooooo  ooooooo
   oooooo   oooooo  oooooo  ooooooo
  oooooooo      oo  oo      oooooooo
  ooooooooooooo oo  oo ooooooooooooo
      oooooooooooo  oooooooooooo
          oooooooo  oooooooo
              oooo  oooo

     ________ ____  _  _____ _   _
    |__  /_ _|  _ \| |/ /_ _| \ | |
      / / | || |_) | ' / | ||  \| |
     / /_ | ||  __/| . \ | || |\  |
    |____|___|_|   |_|\_\___|_| \_|

:: version 2.23.15 :: commit 63365bb ::

2021-12-19 20:15:59.014  INFO [/] 1 --- [oss-http-*:9411] c.l.a.s.Server                           : Serving HTTP at /[0:0:0:0:0:0:0:0%0]:9411 - http://127.0.0.1:9411/
2021-12-19 20:16:39.527  INFO [/] 1 --- [cking-tasks-1-1] z.s.c.Schema                             : Installing schema /zipkin2-schema.cql for keyspace zipkin2
2021-12-19 20:16:45.237  INFO [/] 1 --- [cking-tasks-1-1] z.s.c.Schema                             : Installing indexes /zipkin2-schema-indexes.cql for keyspace zipkin2
2021-12-19 20:16:48.649  INFO [/] 1 --- [ing-tasks-1-177] z.s.c.Schema                             : Upgrading schema /zipkin2-schema-upgrade-1.cql
2021-12-19 20:16:49.819  INFO [/] 1 --- [ing-tasks-1-177] z.s.c.Schema                             : Upgrading schema /zipkin2-schema-upgrade-2.cql
2021-12-19 20:16:52.123  WARN [/] 1 --- [orker-epoll-2-1] z.s.i.BodyIsExceptionMessage             : Unexpected error handling request.
```

But fails for some reason. Restarting zipkin doesn't result in it trying to recreate the schema again, so it just remains in a failure state and I'm not sure how to fix it.

Attempting to run any query results in the following error:

```
com.datastax.oss.driver.api.core.servererrors.InvalidQueryException: table span_by_service does not exist
        at com.datastax.oss.driver.api.core.servererrors.InvalidQueryException.copy(InvalidQueryException.java:48) ~[java-driver-core-4.11.3.jar:?]
        at com.datastax.oss.driver.internal.core.util.concurrent.CompletableFutures.getUninterruptibly(CompletableFutures.java:149) ~[java-driver-core-4.11.3.jar:?]
        at com.datastax.oss.driver.internal.core.cql.CqlPrepareSyncProcessor.process(CqlPrepareSyncProcessor.java:59) ~[java-driver-core-4.11.3.jar:?]
        at com.datastax.oss.driver.internal.core.cql.CqlPrepareSyncProcessor.process(CqlPrepareSyncProcessor.java:31) ~[java-driver-core-4.11.3.jar:?]
        at com.datastax.oss.driver.internal.core.session.DefaultSession.execute(DefaultSession.java:230) ~[java-driver-core-4.11.3.jar:?]
        at com.datastax.oss.driver.api.core.cql.SyncCqlSession.prepare(SyncCqlSession.java:224) ~[java-driver-core-4.11.3.jar:?]
        at zipkin2.storage.cassandra.SelectServiceNames$Factory.<init>(SelectServiceNames.java:34) ~[zipkin-storage-cassandra-2.23.15.jar:?]
        at zipkin2.storage.cassandra.CassandraSpanStore.<init>(CassandraSpanStore.java:86) ~[zipkin-storage-cassandra-2.23.15.jar:?]
        at zipkin2.storage.cassandra.CassandraStorage.spanStore(CassandraStorage.java:164) ~[zipkin-storage-cassandra-2.23.15.jar:?]
        at zipkin2.storage.cassandra.CassandraStorage.serviceAndSpanNames(CassandraStorage.java:176) ~[zipkin-storage-cassandra-2.23.15.jar:?]
        at zipkin2.server.internal.ZipkinQueryApiV2.getRemoteServiceNames(ZipkinQueryApiV2.java:117) ~[classes/:?]
        at com.linecorp.armeria.internal.server.annotation.AnnotatedService.invoke(AnnotatedService.java:391) ~[armeria-1.13.4.jar:?]
        at com.linecorp.armeria.internal.server.annotation.AnnotatedService.lambda$serve0$8(AnnotatedService.java:359) ~[armeria-1.13.4.jar:?]
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
        at com.linecorp.armeria.common.RequestContext.lambda$makeContextAware$3(RequestContext.java:547) ~[armeria-1.13.4.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.70.Final.jar:4.1.70.Final]
        at java.lang.Thread.run(Unknown Source) [?:?]
```

## Steps to Reproduce

Start dockerized zipkin and point it to an existing cassandra instance. Here are my environment vars:

```
STORAGE_TYPE=cassandra3 CASSANDRA_ENSURE_SCHEMA=true CASSANDRA_CONTACT_POINTS=cassandra CASSANDRA_USERNAME=cassandra CASSANDRA_PASSWORD=password
```

## Expected Behaviour

1. Zipkin should be resilient and try to fix/continue a failed migration.
2. Zipkin could output more helpful error messages when failing a migration.
3. Failed migrations should crash Zipkin so operators know there is a problem.
4. Migrations shouldn't fail.

### PR DESCRIPTION
**Pull request by codefromthecrypt**
Before, you couldn't see any error when a health check fails in cassandra for an unresolvable reason. Now you do, including the statement that failed.

This is important as we cannot enable SASI on a running cluster. It must be enabled in whatever starts cassandra.

Fixes https://github.com/openzipkin/zipkin/issues/3412

```bash
$ STORAGE_TYPE=cassandra3 java -jar ./zipkin-server/target/zipkin-server-*exec.jar

                  oo
                 oooo
                oooooo
               oooooooo
              oooooooooo
             oooooooooooo
           ooooooo  ooooooo
          oooooo     ooooooo
         oooooo       ooooooo
        oooooo   o  o   oooooo
       oooooo   oo  oo   oooooo
     ooooooo  oooo  oooo  ooooooo
    oooooo   ooooo  ooooo  ooooooo
   oooooo   oooooo  oooooo  ooooooo
  oooooooo      oo  oo      oooooooo
  ooooooooooooo oo  oo ooooooooooooo
      oooooooooooo  oooooooooooo
          oooooooo  oooooooo
              oooo  oooo

     ________ ____  _  _____ _   _
    |__  /_ _|  _ \| |/ /_ _| \ | |
      / / | || |_) | ' / | ||  \| |
     / /_ | ||  __/| . \ | || |\  |
    |____|___|_|   |_|\_\___|_| \_|

:: version 3.1.1-SNAPSHOT :: commit 47e1668 ::

2024-03-07T08:02:22.739+08:00  INFO [/] 83635 --- [oss-http-*:9411] c.l.a.s.Server                           : Serving HTTP at /[0:0:0:0:0:0:0:0%0]:9411 - http://127.0.0.1:9411/
2024-03-07T08:02:40.128+08:00  INFO [/] 83635 --- [cking-tasks-2-1] z.s.c.Schema                             : Detected Cassandra version 4.1.4
2024-03-07T08:02:40.128+08:00  INFO [/] 83635 --- [cking-tasks-2-1] z.s.c.Schema                             : Installing schema /zipkin2-schema.cql for keyspace zipkin2
2024-03-07T08:02:46.044+08:00  INFO [/] 83635 --- [cking-tasks-2-1] z.s.c.Schema                             : Installing indexes /zipkin2-schema-indexes.cql for keyspace zipkin2
2024-03-07T08:02:47.184+08:00 ERROR [/] 83635 --- [cking-tasks-2-1] z.s.c.Schema                             : Failed to execute [CREATE CUSTOM INDEX IF NOT EXISTS ON zipkin2.span (l_service) USING 'org.apache.cassandra.index.sasi.SASIIndex'
   WITH OPTIONS = {'mode': 'PREFIX'}]: SASI indexes are disabled. Enable in cassandra.yaml to use.
```

### CODE REVIEW

**Comment by codefromthecrypt** [comment]
I'm going to set this down a while because this is all about giving a better message when SASI is disabled when it must be enabled. The problem is the message that it is disabled is only visible once as it isn't logged.

**Comment by codefromthecrypt** [comment]
what's needed here next is to get unit tests passing again. I think the logs are correct now. @reta if you have time you can give a swing on this branch. I'm way over time since 3.1 stuff and have to focus on work a few day to a week. see you around!

File: zipkin-storage/cassandra/src/main/java/zipkin2/storage/cassandra/Schema.java [hunk 1]
```diff
@@ -126,18 +185,26 @@ static boolean hasUpgrade2_remoteService(KeyspaceMetadata keyspaceMetadata) {
...
+        // be visible in API error responses, such as /health or /api/v2/traces.
+        LOG.error(message);
+        throw new RuntimeException(message, e);
+      }
     }
   }
 
   static String reviseCQL(Version version, String cql) {
-    if (version.getMajor() == 4) {
+    if (version.getMajor() >= 4) {
```
Comment (codefromthecrypt) [inline zipkin-storage/cassandra/src/main/java/zipkin2/storage/cassandra/Schema.java:207]: PS I won't be making a cassandra 5 image as it is still beta, but FYI with this people can try on own.. provided they enable SASI in cassandra.yaml like this:

```diff
diff --git a/zipkin-storage/cassandra/pom.xml b/zipkin-storage/cassandra/pom.xml
index 417887e2b..c6e67df63 100644
--- a/zipkin-storage/cassandra/pom.xml
+++ b/zipkin-storage/cassandra/pom.xml
@@ -99,5 +99,11 @@
       <artifactId>jnr-posix</artifactId>
       <version>3.1.19</version>
     </dependency>
+    <dependency>
+      <groupId>org.testcontainers</groupId>
+      <artifactId>cassandra</artifactId>
+      <version>${testcontainers.version}</version>
+      <scope>test</scope>
+    </dependency>
   </dependencies>
 </project>
diff --git a/zipkin-storage/cassandra/src/test/java/zipkin2/storage/cassandra/CassandraContainer.java b/zipkin-storage/cassandra/src/test/java/zipkin2/storage/cassandra/CassandraContainer.java
index 536738e49..96cf46257 100644
--- a/zipkin-storage/cassandra/src/test/java/zipkin2/storage/cassandra/CassandraContainer.java
+++ b/zipkin-storage/cassandra/src/test/java/zipkin2/storage/cassandra/CassandraContainer.java
@@ -16,9 +16,8 @@ import java.util.List;
 import java.util.Optional;
 import org.slf4j.Logger;
 import org.slf4j.LoggerFactory;
-import org.testcontainers.containers.GenericContainer;
 import org.testcontainers.containers.output.Slf4jLogConsumer;
-import org.testcontainers.containers.wait.strategy.Wait;
+import org.testcontainers.utility.MountableFile;
 
 import static org.assertj.core.api.Assertions.assertThat;
 import static org.junit.jupiter.api.Assumptions.assumeTrue;
@@ -28,14 +27,16 @@ import static zipkin2.storage.cassandra.ITCassandraStorage.SEARCH_TABLES;
 import static zipkin2.storage.cassandra.Schema.TABLE_DEPENDENCY;
 import static zipkin2.storage.cassandra.Schema.TABLE_SPAN;
 
-class CassandraContainer extends GenericContainer<CassandraContainer> {
+class CassandraContainer
+  extends org.testcontainers.containers.CassandraContainer<CassandraContainer> {
   static final Logger LOGGER = LoggerFactory.getLogger(CassandraContainer.class);
   CqlSession globalSession;
 
   CassandraContainer() {
-    super(parse("ghcr.io/openzipkin/zipkin-cassandra:3.1.0"));
-    addExposedPort(9042);
-    waitStrategy = Wait.forHealthcheck();
+    super(parse("cassandra:5.0-beta1"));
+    // edited to sasi_indexes_enabled: true
+    withCopyFileToContainer(
+      MountableFile.forClasspathResource("cassandra.yaml", 0_600),
+      "/etc/cassandra/cassandra.yaml");
     withLogConsumer(new Slf4jLogConsumer(LOGGER));
   }
```

Comment (codefromthecrypt) [reply zipkin-storage/cassandra/src/main/java/zipkin2/storage/cassandra/Schema.java:207]: on my laptop all tests are green with above, fyi, with cassandra 5
