### PR TITLE
Handles RFC 7159 json escaping

### LINKED ISSUE #1272: Error executing query: server error (parsererror) in Zipkin 1.8
I got `Error executing query: server error (parsererror)` when trying to find traces. This happens after update from Zipkin 1.7.0 to 1.8.2 today. Spans that I send are somehow problematic for the newer version of Zipkin. I get `202 Accepted` response every time.

JSON:

```
[
  {
    "traceId": "5e1b76cb257aa6fd",
    "name": "app - root span",
    "id": "168ba9a2869c3ae1",
    "timestamp": 1473066067938000,
    "duration": 484655,
    "annotations": [
      {
        "timestamp": 1473066067938000,
        "value": "sr",
        "endpoint": {
          "serviceName": "app",
          "ipv4": "0.0.0.0"
        }
      },
      {
        "timestamp": 1473066068422655,
        "value": "ss",
        "endpoint": {
          "serviceName": "app",
          "ipv4": "0.0.0.0"
        }
      }
    ],
    "binaryAnnotations": []
  },
  {
    "traceId": "5e1b76cb257aa6fd",
    "name": "app test - get",
    "id": "fbbff4adc94c01cb",
    "parentId": "168ba9a2869c3ae1",
    "timestamp": 1473066067939000,
    "duration": 483823,
    "annotations": [],
    "binaryAnnotations": [
      {
        "key": "error",
        "value": "org.sql2o.Sql2oException: Database error: ORA-00942: table or view does not exist\n",
        "endpoint": {
          "serviceName": "app",
          "ipv4": "0.0.0.0"
        }
      },
      {
        "key": "lc",
        "value": "Application",
        "endpoint": {
          "serviceName": "app",
          "ipv4": "0.0.0.0"
        }
      }
    ]
  }
]
```

### PR DESCRIPTION
**Pull request by codefromthecrypt**
We accept data that might violate json escaping rules. This escapes
any UTF-8 String we accept, even binary annotations.

Fixes #1272

### CODE REVIEW

File: zipkin/src/main/java/zipkin/internal/JsonCodec.java [hunk 1]
```diff
@@ -235,14 +236,14 @@ public BinaryAnnotation fromJson(JsonReader reader) throws IOException {
...
-      sizeInBytes += asciiSizeInBytes("{\"key\":\"") + utf8SizeInBytes(value.key);
+      sizeInBytes += asciiSizeInBytes("{\"key\":\"") + jsonEscapedSizeInBytes(value.key);
       sizeInBytes += asciiSizeInBytes("\",\"value\":");
       switch (value.type) {
         case BOOL:
           sizeInBytes += asciiSizeInBytes(value.value[0] == 1 ? "true" : "false");
           break;
         case STRING:
-          sizeInBytes += value.value.length +2; //for quotes
+          sizeInBytes += jsonEscapedSizeInBytes(value.value) + 2; //for quotes
```
Comment (codefromthecrypt) [inline zipkin/src/main/java/zipkin/internal/JsonCodec.java:246]: this was the bugger. the raised issue had special characters in a binary annotation! for json encoding, we need to peek at it.
