### PR TITLE
Fixes int overflow issue for large TTL values

### LINKED ISSUE #3357: timestampRange calculation error due to int variable instead of long
timestampRange calculation error due to int variable instead of long

CassandraSpanStore.java

Change needed from:
final int indexTtl;

To:
final long indexTtl

It will calculate wrong if TTL from table is set for 7890000.

The result will be a bucket from the future.

### PR DESCRIPTION
**Pull request by vy8**
Fixes #3357.

The line `indexTtl * 1000` will produce an integer overflow for large indexTtl values. For example 7890000 * 1000 will produce an integer overflow (some negative number).

The simple fix is to use long in the multiplication.

### CODE REVIEW

**Comment by jcchavezs** [comment]
Ping @anuraaga

**Comment by jcchavezs** [comment]
@vy8 could you add a unit test for this?

**Comment by vy8** [comment]
Hey @jcchavezs just did. Even thought it's a simple test that checks if startMillis is smaller than endMillis it will fail with the old code that doesn't have the explicit 'L' for long.

File: zipkin-storage/cassandra/src/main/java/zipkin2/storage/cassandra/CassandraSpanStore.java [hunk 1]
```diff
@@ -305,8 +305,8 @@
     UUID endUUID;
   }
 
-  TimestampRange timestampRange(QueryRequest request) {
-    long oldestData = Math.max(System.currentTimeMillis() - indexTtl * 1000, 0); // >= 1970
+  TimestampRange timestampRange(QueryRequest request, int indexTtl) {
```
Comment (jcchavezs) [inline zipkin-storage/cassandra/src/main/java/zipkin2/storage/cassandra/CassandraSpanStore.java:308]: Do we truly need to pass indexTtl as param? I see this is a class attribute: https://github.com/openzipkin/zipkin/pull/3367/files#diff-d85e858924df5caed00b20b67deac8389b768227fc7fdf8f7575884ae941a663L54

Comment (vy8) [reply zipkin-storage/cassandra/src/main/java/zipkin2/storage/cassandra/CassandraSpanStore.java:308]: @jcchavezs the indexTtl value comes from a static method and then gets set to a final class attribute. To create a test I need to either:
a) Set the property using reflection for the test.
b) Mock a static method.
c) Pass the indexTtl as a param.

I chose c) since it seemed as the least amount of hassle. Tell me which option you would prefer and I'll implement it.
Cheers!

**Comment by jcchavezs** [comment]
Somehow the test is failing. Would you please look into it?

**Comment by vy8** [comment]
@jcchavezs bumped the year in the license from 2020 to 2021 and all should be good.

**Comment by codefromthecrypt** [comment]
thanks. will be in next release
