### PR TITLE
Stops looking for local RabbitMQ connection

### LINKED ISSUE #1748: RabbitMQ integration test fails on Travis
We currently have a rabbitmq service added to travis config because the test-containers config fails with connect errors.

### PR DESCRIPTION
**Pull request by codefromthecrypt**
This improves the Docker based RabbitMQ tests in the same manner as
https://github.com/openzipkin/zipkin-reporter-java/pull/176

This notably stops looking for a local RabbitMQ install. It also reduces
flakes by using the CLI and not sharing static collector resources in
instance-level tests.

Fixes #1748

### CODE REVIEW

File: zipkin-collector/rabbitmq/src/test/java/zipkin2/collector/rabbitmq/ITRabbitMQCollector.java [hunk 1]
```diff
@@ -15,151 +15,120 @@
...
 public class ITRabbitMQCollector {
   List<Span> spans = Arrays.asList(LOTS_OF_SPANS[0], LOTS_OF_SPANS[1]);
 
-  @ClassRule
-  public static RabbitMQCollectorRule rabbit = new RabbitMQCollectorRule("rabbitmq:3.7-alpine");
+  @ClassRule public static RabbitMQCollectorRule rabbit = new RabbitMQCollectorRule();
 
-  @After
-  public void clear() {
-    rabbit.metrics.clear();
```
Comment (codefromthecrypt) [inline zipkin-collector/rabbitmq/src/test/java/zipkin2/collector/rabbitmq/ITRabbitMQCollector.java:48]: a lot of flakes are possible when static java connections and such are used for test methods.. It is very true that rabbit itself should be instantiated once per (suite if possible) as it is slow to start.

File: zipkin-collector/rabbitmq/src/test/java/zipkin2/collector/rabbitmq/ITRabbitMQCollector.java [hunk 2]
```diff
@@ -15,151 +15,120 @@
...
-    rabbit.publish(malformed2);
-    rabbit.publish(THRIFT.encodeList(spans));
+    publish(THRIFT.encodeList(spans));
+    publish(new byte[0]);
+    publish(malformed1);
+    publish(malformed2);
+    publish(THRIFT.encodeList(spans));
 
-    Thread.sleep(1000);
+    Thread.sleep(200L);
```
Comment (codefromthecrypt) [inline zipkin-collector/rabbitmq/src/test/java/zipkin2/collector/rabbitmq/ITRabbitMQCollector.java:88]: As far as I know rabbit is push not poll, so any delay here would be how long it can decode the message and synchronously add to our in-memory storage. 200L is a bit excessive but less slow than 1s

**Review by jorgheymans — APPROVED** [review]
Nice cleanup, a lot more involved than what i had in mind !

**Comment by codefromthecrypt** [comment]
thanks for keeping the project eyes focused @jorgheymans !
