### PR TITLE
Default unsupported locales to English.

### LINKED ISSUE #3034: Pagination on the result page broken
Hello,

I just updated to 2.20.2 and when doing a search, I get the following on the top instead of the number of results/pagination:

`{0, plural, one {# Result} other {# Results}}`

### PR DESCRIPTION
**Pull request by anuraaga**
Even with good hints on what causes the issue, I still can't reproduce locally. Have tried changing browser language and hacking the code to return an unsupported locale and things always work fine for me.

But anyways, by ensuring the app locale is only ever a supported locale, I'm guessing any issues will go away.

Fixes #3034 hopefully

### CODE REVIEW

File: zipkin-lens/src/util/locale.ts [hunk 1]
```diff
@@ -12,25 +12,49 @@
...
+  if (hyphenIndex >= 0) {
+    const stripped = browserLanguage.substring(0, hyphenIndex);
+    if (catalogs.hasOwnProperty(stripped)) {
+      return stripped;
+    }
   }
 
-  return browserLanguage;
+  // Default to English if we don't support the current browser language.
+  return 'en';
```
Comment (codefromthecrypt) [inline zipkin-lens/src/util/locale.ts:50]: guessing this is the key

**Review by codefromthecrypt — APPROVED** [review]
